apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: multiplier-deployment
spec:
  selector:
    matchLabels:
      app: multiplier
  replicas: 1
  template:
    metadata:
      labels:
        app: multiplier
    spec:
      containers:
        - name: multiplier
          image: nikmakarov/multiplier:1.7
          ports:
            - containerPort: 8080